# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-ollama-study',
                'doc_host': 'https://MagariDIS.github.io',
                'git_url': 'https://github.com/MagariDIS/nbdev-ollama-study',
                'lib_path': 'nbdev_ollama_study'},
  'syms': {'nbdev_ollama_study.core': {'nbdev_ollama_study.core.foo': ('core.html#foo', 'nbdev_ollama_study/core.py')}}}
